version: "3"
services:
  # reverse proxy
  reverse_proxy:
    image: nginx:alpine
    #restart : always
    # maps config file into the proxy container
    volumes:
      - ./node-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    #  - 443:443
    links:
      - sigo_normas
      - sigo_website

  sigo_normas:
    image: sigo/normas:dev
    #restart: always
    env_file: ./docker-compose.env
    environment:
    - ASPNETCORE_ENVIRONMENT=Development

  sigo_website:
    image: sigo/website:dev
    #restart: always
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - PathBase=/sigo/website
